config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  
  resources :bookings, only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'from_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'to_id'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers
  
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from, class_name: 'Airport'
  belongs_to :to, class_name: 'Airport'
  has_many :bookings
  
  default_scope -> { order(:start) }
  
  def from_city
    from.city
  end
  
  def to_city
    to.city
  end
  
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
  
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def new
    unless params[:flight_id]
      flash[:error] = "You have not selected a flight."
      redirect_to session.delete(:return_to) and return
    end
    
    flight = Flight.find(params[:flight_id])  
    @booking = flight.bookings.build
    params[:passengers].to_i.times do
      @booking.passengers.build      
    end
  end
  
  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      send_confirmation_emails
      redirect_to @booking
    else
      flash.now[:error] = "All fields are required."
      render :new
    end
  end
  
  
  def show
    @booking = Booking.find(params[:id])
  end
  
  private
  
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
    
    def send_confirmation_emails
      flight = Flight.find(params[:booking][:flight_id])
      params[:passengers].to_i.times do |i|
        passenger_name = params[:booking][:passengers_attributes][i.to_s][:name]
        passenger_email = params[:booking][:passengers_attributes][i.to_s][:email]
        PassengerMailer.thank_you_email(flight, passenger_name, passenger_email).deliver
      end
    end
    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index
    @airports = Airport.all
    
    if params[:from] && params[:to] && params[:date]
      start_date = Time.new(*params[:date].split('-'))
      end_date = start_date + 1.day
      @flights = Flight.where(from_id: params[:from], to_id: params[:to],
                              start: (start_date...end_date))
      session[:return_to] = request.original_url
        
      if @flights.empty?
        dates = Flight.pluck(:start)
        min_date = dates.min.strftime("%d %b %Y")
        max_date = dates.max.strftime("%d %b %Y")
        flash.now[:error] = "Oops, it appears that there are no flights matching"\
        " your criteria. Tip: Make sure you are selecting a date between #{min_date} and"\
        " #{max_date}."
      end
    end
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  
  def duration_from_minutes(minutes)
    (minutes/60).to_s + ':' + (minutes % 60).to_s.rjust(2, '0')
  end
  
end

app/views/bookings/new.html.erb
<% provide :header, "New booking" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>You are booking a flight no. <strong><%= @booking.flight.id %></strong> from
    <strong><%= @booking.flight.from.city %></strong> to
    <strong><%= @booking.flight.to.city %></strong> departing on
    <strong><%= @booking.flight.start.strftime("%d %B %Y") %></strong> at
    <strong><%= @booking.flight.start.strftime("%H:%M") %></strong>.</p>
    <p>Please enter passenger information below.</p>
  <%= form_for @booking do |f| %>
    <%= f.hidden_field_tag 'passengers', params[:passengers] %>
    <%= f.hidden_field :flight_id %>
    <% @booking.passengers.each.with_index do |passenger, index| %>
      <%= f.fields_for :passengers, passenger do |passengers_f| %>
        <h2>Passenger <%= index + 1 %></h2>
        <div class="form-group">
          <%= passengers_f.label :name %>
          <%= passengers_f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= passengers_f.label :email %>
          <%= passengers_f.email_field :email, class: 'form-control' %>
        </div>
      <% end %>
    <% end %>
    <%= f.submit 'Confirm booking', class: 'btn btn-primary' %>
  <% end %>
  
  </div>
</div>

app/views/bookings/show.html.erb
<% provide :header, 'Booking confirmation' %>

<div class="row text-left">
  <div class="col-md-6 col-md-offset-3">
    
    <h2>Your flight details</h2>
    <table class="table">
      <tr>
        <th>From</th>
        <td><%= @booking.flight.from.city %></td>
      </tr>
      <tr>
        <th>To</th>
        <td><%= @booking.flight.to.city %></td>
      </tr>
      <tr>
        <th>Flight number</th>
        <td><%= @booking.flight.id %></td>
      </tr>
      <tr>
        <th>Date</th>
        <td><%= @booking.flight.start.strftime("%d %B %Y") %></td>
      </tr>
      <tr>
        <th>Departure time</th>
        <td><%= @booking.flight.start.strftime("%H:%M") %></td>
      </tr>
      <tr>
        <th>Duration</th>
        <td><%= duration_from_minutes(@booking.flight.duration) %></td>
      </tr>
    </table>
    
    <% @booking.passengers.each.with_index do |passenger, index| %>
      <h2>Passenger <%= index + 1 %></h2>
      <table class="table">
        <tr>
          <th>Name</th>
          <td><%= passenger.name %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= passenger.email %></td>
        </tr>
      </table>
    <% end %>
    
  </div>
</div>

app/views/flights/index.html.erb
<% provide :header, 'Flight booker' %>

<div class="row">
  <%= form_tag '/', method: :get do %>
    <div class="col-md-3 form-group">
      <%= label_tag 'from' %>
      <%= select_tag 'from', options_from_collection_for_select(@airports, 'id', 'city', params[:from] || 1), class: 'form-control' %>
    </div>
    <div class="col-md-3 form-group">
      <%= label_tag 'to' %>
      <%= select_tag 'to', options_from_collection_for_select(@airports, 'id', 'city', params[:to] || 2), class: 'form-control' %>
    </div>
    <div class="col-md-3 form-group">
      <%= label_tag 'date' %>
      <%= date_field_tag 'date', params[:date] || Time.now.strftime("%Y-%m-%d"), class: 'form-control' %>
    </div>
    <div class="col-md-3 form-group">
      <%= label_tag 'passengers' %>
      <%= select_tag 'passengers', options_for_select([[1, 1], [2, 2], [3, 3], [4, 4]], params[:passengers] || 1), class: 'form-control', id: 'passengers_dropdown' %>
    </div>
    <%= submit_tag 'Find flights', class: 'btn btn-primary' %>
  <% end %>
</div>

<% unless !@flights || @flights.empty? %>
  <div class="row">
    <%= form_tag new_booking_path, method: :get do %>
      <%= hidden_field_tag 'passengers', params[:passengers], id: 'passengers_hidden' %>
      <table class="table table-striped text-left">
        <tr>
          <th></th>
          <th>From</th>
          <th>To</th>
          <th>Departure time</th>
          <th>Duration</th>
        </tr>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= radio_button_tag 'flight_id', flight.id %></td>
            <td><%= flight.from.city %></td>
            <td><%= flight.to.city %></td>
            <td><%= flight.start.strftime("%H:%M") %></td>
            <td><%= duration_from_minutes(flight.duration) %></td>
          </tr>
        <% end %>
      </table>
      <%= submit_tag 'Book', class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,100' rel='stylesheet' type='text/css'>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container text-center">
    
    <div class="row">
      <div class="col-xs-12">
        <h1><%= yield(:header) %></h1>
        <nav>
          <ul>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', page_path('about') %></li>
          </ul>
        </nav>
      </div>
    </div>
    
    <% if flash[:error] %>
      <div class="row">
        <div class="col-xs-12">
          <p class="flash-message"><%= flash[:error] %></p>        
        </div>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag 'plane.jpg', alt: 'Airplane drawn in pencil' %>
      </div>
    </div>
    
    <%= yield %>
    
  </div>
  
</body>
</html>

app/views/pages/about.html.erb
<% provide :header, 'About' %>

<div class="row">
  <div class="col-xs-12 text-left about">
    <p>This page is an exercise in building advanced forms with Ruby on Rails. It completes the <%= link_to 'Advanced Forms', 'http://www.theodinproject.com/ruby-on-rails/building-advanced-forms' %> chapter of the Ruby on Rails section of
    <%= link_to 'The Odin Project', 'http://www.theodinproject.com' %>, an open source curriculum for teaching web development.</p>
    <p>My name is Hubert Pompecki. To see more of my work, including a Twitter clone, an event management app and chess written in Ruby, please visit my <%= link_to 'GitHub profile', 'https://github.com/hp-4k' %>.</p>
  </div>
</div>